[project]
name = "mobilize"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp",
    "asyncio",
    "yarl",
    "aiogram",
    "python-dotenv",
    "langchain",
    "langchain-ollama",
]
